    version: '3.2'
    services:
      prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
        - 9090:9090
        command:
        - --config.file=/etc/prometheus/prometheus.yml
        - --web.external-url=http://localhost/prometheus
        volumes:
        - /etc/prometheus/:/etc/prometheus/:ro
        depends_on:
        - cadvisor
        - node_exporter
      cadvisor:
        image: google/cadvisor:latest
        container_name: cadvisor
        ports:
        - 8080:8080
        volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        cap_add: 
        - SYS_TIME
        depends_on:
        - redis
      redis:
        image: redis:latest
        container_name: redis
        ports:
        - 6379:6379
      node_exporter: 
        image: quay.io/prometheus/node-exporter
        container_name: node_exporter
        pid: "host"
        volumes:
        - /:/host:ro,rslave
        ports: 
        - 9100:9100
        cap_add: 
        - SYS_TIME
      grafana:
        image: grafana/grafana
        container_name: grafana
        depends_on:
        - prometheus
        ports:
        - 3000:3000
        volumes:
        - grafana-config:/etc/grafana:rw
        - grafana-data:/var/lib/grafana:rw
        - grafana-home:/usr/share/grafana:rw
        environment:
          GF_SERVER_DOMAIN: localhost:3000
          GF_SERVER_ROOT_URL: http://localhost:3000/grafana/
          GF_AUTH_BASIC_ENABLED: "true"
          GF_AUTH_PROXY_ENABLED: "true"
          GF_AUTH_PROXY_HEADER_NAME: "X-WEBAUTH-USER"
          GR_USERS_ALLOW_SIGN_UP: "false"
          GF_SECURITY_ADMIN_PASSWORD: secret
          GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
          GF_SECURITY_ADMIN_USER: admin
          GF_DATABASE_TYPE: mysql
          GF_DATABASE_HOST: 192.168.0.192:3306
          GF_DATABASE_NAME: grafana_db
          GF_DATABASE_USER: grafana_user
          GF_DATABASE_PASSWORD: secret
      web:
        image: nginx
        restart: always
        volumes:
         - /root/nginx/:/etc/nginx/:ro
        ports:
         - "443:443"
        environment:
         - NGINX_HOST=localhost
         - NGINX_PORT=443
        depends_on: 
         - prometheus
         - grafana
    volumes:
      grafana-config:
      grafana-data:
      grafana-home: