apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: grafana-data
  name: grafana-data
spec:
  storageClassName: longhorn-nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
status: {}
