apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: grafana-provisioning
  name: grafana-provisioning
spec:
  storageClassName: longhorn-nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
