apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-provisioning
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: longhorn-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /grafana_data_prov
    server: 10.116.0.8 
