apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 -v convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: alertmanager
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alertmanager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 -v convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/back-tier: "true"
        io.kompose.service: alertmanager
    spec:
      containers:
      - args:
        - --config.file=/etc/alertmanager/config.yml
        - --storage.path=/alertmanager
        image: prom/alertmanager:v0.21.0
        imagePullPolicy: IfNotPresent
        name: alertmanager
        ports:
        - containerPort: 9093
        resources: {}
        volumeMounts:
        - mountPath: /etc/alertmanager/config.yml
          subPath: config.yml
          name: alertmanager-configmap-volume
        - mountPath: /alertmanager
          name: alertmanager-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: alertmanager-configmap-volume
        configMap:
          name: alertmanager-configmap
      - name: alertmanager-data
        persistentVolumeClaim:
          claimName: alertmanager-data
status: {}
