apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 -v convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: alertmanager
  name: alertmanager
spec:
  ports:
  - name: "9093"
    port: 9093
    nodePort: 30093
    targetPort: 9093
  selector:
    io.kompose.service: alertmanager
  type: NodePort
status:
  loadBalancer: {}
