apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: longhorn-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data
    server: 10.108.0.2
