apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  labels:
    application: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      evaluation_interval: 30s
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093       
    rule_files:
      - "/etc/config/alert.rules"      
    
    remote_write:
    - url: "http://influxdb:8086/api/v1/prom/write?u=icaroAdmin&p=Icaro@dmin123&db=prometheusdb"

    remote_read:
    - url: "http://influxdb:8086/api/v1/prom/read?u=icaroAdmin&p=Icaro@dmin123&db=prometheusdb"

    scrape_configs:
    - job_name: 'node_exporter_consul'
      consul_sd_configs:
      - server: 'consul:8500'
        services: ['k3sMaster_node_exporter','k3s_node_exporter']
      relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*,_service=([^,]+),.*
        replacement: ${1}
        target_label: _service
      - source_labels: [__meta_consul_tags]
        regex: .*,_hostname=([^,]+),.*
        replacement: ${1}
        target_label: _hostname
      - source_labels: [__meta_consul_tags]
        regex: .*,_environment=([^,]+),.*
        replacement: ${1}
        target_label: _environment
      - source_labels: [__meta_consul_tags]
        regex: .*,_cluster=([^,]+),.*
        replacement: ${1}
        target_label: _cluster         