apiVersion: v1
kind: Service
metadata:
  name: sql-exporter
  labels:
    name: sql-exporter
spec:
  clusterIP: None
  ports:
    - name: http
      port: 9399
      targetPort: 9399
  selector:
    app: sql-exporter
