---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- files-influxdb-env-configmap.yaml  
- influxdb-data-persistentvolumeclaim.yaml  
- influxdb-deployment.yaml  
- influxdb-service.yaml